CI: use Scilab to create the archive_test_results.csv report
See https://gitlab.com/scilab/scilab/-/merge_requests/1224

diff --git a/.gitlab-ci/publish.yml b/.gitlab-ci/publish.yml
--- a/.gitlab-ci/publish.yml
+++ b/.gitlab-ci/publish.yml
@@ -27,19 +27,84 @@ index_gitlab_pages:
       - public
   when: always
 
+# Create a new linux_runner:${DOCKER_TAG} from a downloaded binary
+create_linux_runner:
+  stage: publish
+  image: docker:20.10.16
+  tags: [x86_64-linux-gnu, docker, scilab, build]
+  needs: []
+  variables:
+    GIT_CLEAN_FLAGS: "none"
+    DISTRO: "ubuntu-20.04"
+  script:
+    - |
+      if [[ "$DOCKER_TAG" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+        echo "invalid DOCKER_TAG variable: expecting a Scilab X.Y.Z version"
+        exit 1
+      fi
+    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
+    - |
+      docker build -t ${SCI_REGISTRY_IMAGE}/linux_runner:${DOCKER_TAG} - <<EOF
+      FROM ${SCI_REGISTRY_IMAGE}/${DISTRO}:${DOCKER_TAG}
+      USER root
+      RUN curl -L https://www.scilab.org/download/${DOCKER_TAG}/scilab-${DOCKER_TAG}.bin.x86_64-linux-gnu.tar.xz | tar xJf - -C /opt/
+      USER scilab
+      ENV PATH="${PATH}:/opt/scilab-${DOCKER_TAG}/bin"
+      EOF
+    - docker image tag ${SCI_REGISTRY_IMAGE}/linux_runner:${DOCKER_TAG} ${SCI_REGISTRY_IMAGE}/linux_runner:latest
+    - docker push ${SCI_REGISTRY_IMAGE}/linux_runner:${DOCKER_TAG}
+    - docker logout "${CI_REGISTRY}"
+  when: manual
+
 # generate an archive of all tests files and logs
 archive_test_results:
   stage: publish
   tags: [x86_64-linux-gnu, docker, scilab]
-  image: ${SCI_REGISTRY_IMAGE}/linux-builder:${DOCKER_TAG}
+  image: registry.gitlab.com/scilab/scilab/linux-runner:latest
   variables:
     GIT_STRATEGY: none
   script:
-    - echo "${SCI_VERSION_STRING} ${CI_COMMIT_TIMESTAMP} ${CI_COMMIT_SHORT_SHA};tests;errors;failures" >${SCI_VERSION_STRING}/archive_test_results.csv
-    - awk 'BEGIN{FS="\""; OFS=";"} /\<testsuite /{print $2,$6,$8,$10; }' ${SCI_VERSION_STRING}/*/*.xml |sort -t\; >>${SCI_VERSION_STRING}/archive_test_results.csv
-    - while IFS=";" read name tests errors failures ; do printf "%-40s%10s%10s%10s\n" "$name" "$tests" "$errors" "$failures"; done <${SCI_VERSION_STRING}/archive_test_results.csv
+    - |
+      scilab -nwni <<EOF
+      dirs = ls(getenv("SCI_VERSION_STRING") + "/*");
+      results = ls(dirs + "/*.xml");
+
+      csv = emptystr(size(dirs, 1), 4);
+      names = basename(results);
+      for i=1:size(results, 1)
+          doc = xmlRead(results(i));
+          xp = xmlXPath(doc, "//testsuites/testsuite");
+          if size(xp) <> [1 1] then
+              csv(i, 1) = "unable to read report"
+              continue
+          end
+          testsuite = xp(1);
+
+          csv(i, 1) = xmlXPath(testsuite, "./@tests").content;
+          csv(i, 2) = xmlXPath(testsuite, "./@errors").content;
+          csv(i, 3) = xmlXPath(testsuite, "./@failures").content;
+          res = xmlXPath(testsuite, "./testcase[./failure|./error]/@name");
+          buggy = [""];
+          for j = 1:length(res)
+              buggy = [buggy res(j).content];
+          end
+          csv(i, 4) = strcat(gsort(buggy, "lr", "i"), " ");
+          xmlDelete(doc)
+      end
+
+      t = matrix2table(csv, "VariableNames", ["tests", "errors", "failures", "test names"], "RowNames", names);
+      t.Properties.Description = strcat([getenv("SCI_VERSION_STRING") getenv("CI_COMMIT_TIMESTAMP", "") getenv("CI_COMMIT_SHORT_SHA", "")], " ");
+      writetable(t, "archive_test_results.csv", "WriteVariableNames", %t, "WriteRowNames", %t);
+      
+      lines(0, 320)
+      disp(t)
+
+      exit(0)
+      EOF
   allow_failure: true
+  when: always
   artifacts:
+    when: always
     paths:
       - "${SCI_VERSION_STRING}/archive_test_results.csv"
       - "${SCI_VERSION_STRING}/*/*.xml"
